### ISSUE TITLE
Option to filter out sourcemap

### ISSUE THREAD

**Issue by TxHawks** [lucleray/next-size#3]
Currently, sourcemaps are included in the report, which clutters the list, as their size  isn't something you're likely to care about. 

I think they should be filtered out by default, possibly with an option to bring them back if someone does care about their sizes.

Alternatively, an option to remove them would also be helpful

**Comment by lucleray** [comment]
Good point!

I'm not using sourcemaps myself, could you share a screenshot of how they look like?

**Comment by TxHawks** [comment]
Can do later, not next to a computer at the moment, but basically, a `.js.map` file is generated for each chunk, so `chunk1[hash].js` will have `chunk1[hash].js.map`.

This can obviously add up in large apps

**Comment by lucleray** [comment]
Published in [`2.0.2`](https://github.com/lucleray/next-size/releases/tag/2.0.2).

**Comment by TxHawks** [comment]
Thanks
